USE SQLQueryCrackers
GO
 
--CREATE SCHEMA ONCASCADE
--GO
DROP TABLE IF EXISTS ONCASCADE.GrandChild
GO
DROP TABLE IF EXISTS ONCASCADE.Child2
GO
DROP TABLE IF EXISTS ONCASCADE.Child1
GO
DROP TABLE IF EXISTS ONCASCADE.Parent
GO

CREATE  TABLE ONCASCADE.Parent
(
	ParentID INT IDENTITY(1,1) PRIMARY KEY 	
	,Data VARCHAR(100) 
)

CREATE  TABLE ONCASCADE.Child1
(
	Child1ID INT IDENTITY(1,1) PRIMARY KEY
	,ParentID INT REFERENCES ONCASCADE.Parent(ParentID) ON DELETE CASCADE
	,Data VARCHAR(100)
)


CREATE  TABLE ONCASCADE.Child2
(
	Child2ID INT IDENTITY(1,1) PRIMARY KEY

	,ParentID INT REFERENCES ONCASCADE.Parent(ParentID) ON DELETE CASCADE
	,Data VARCHAR(100)
)

CREATE  TABLE ONCASCADE.GrandChild
(
	GrandChildID INT IDENTITY(1,1) PRIMARY KEY
	,Child1ID INT  REFERENCES ONCASCADE.Child1(Child1ID) ON DELETE CASCADE
	,Child2ID INT REFERENCES ONCASCADE.Child2(Child2ID) --ON DELETE CASCADE
	,Data VARCHAR(100)
)

--DROP   TABLE ONCASCADE.Parent
--DROP   TABLE ONCASCADE.Child1
--DROP   TABLE ONCASCADE.Child2
--DROP   TABLE ONCASCADE.GrandChild